from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from afr_glyphcore import FEATURE_COUNT, FEATURE_SCHEMA_VERSION  # noqa: E402

MINIMUM_CONFIDENCE = 0.92
MINIMUM_SCORE_MARGIN = 0.18
AI_DISPLAY_NAME = "文枢"
AI_INTERNAL_NAME = "GlyphCore"
AUTHOR_NAME = "splrad 秋夕寻星"
AUTHOR_EMAIL = "alearner@splrad.com"
PROJECT_GITHUB = "https://github.com/splrad/CADFontAutoReplace"
PROJECT_GITEE = "https://gitee.com/splrad/CADFontAutoReplace"


def main() -> int:
    parser = argparse.ArgumentParser(description="Train AFR DBText AI LightGBM scorer and export ONNX.")
    parser.add_argument("--features", required=True, help="Feature CSV generated by build_features.py.")
    parser.add_argument("--output-dir", required=True, help="Model output directory.")
    parser.add_argument("--seed", type=int, default=20260512)
    parser.add_argument("--opset", type=int, default=12)
    parser.add_argument("--max-false-repair-rate", type=float, default=0.001)
    parser.add_argument("--skip-onnx", action="store_true", help="Train and report without exporting ONNX.")
    args = parser.parse_args()

    try:
        import numpy as np
        import pandas as pd
        import lightgbm as lgb
    except ImportError as ex:
        print(f"missing training dependency: {ex}", file=sys.stderr)
        print("install with: python -m pip install -r AFR.GlyphCore/tools/requirements.txt", file=sys.stderr)
        return 10

    features_path = Path(args.features)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    stale_exact_repairs = output_dir / "AFR.GlyphCore.ExactRepairs.json"
    if stale_exact_repairs.exists():
        stale_exact_repairs.unlink()

    df = pd.read_csv(features_path, encoding="utf-8-sig")
    feature_cols = [col for col in df.columns if re.match(r"^f\d{2}_", col)]
    if len(feature_cols) != FEATURE_COUNT:
        raise ValueError(f"expected {FEATURE_COUNT} feature columns, got {len(feature_cols)}")

    train_groups, valid_groups, test_groups = split_groups(df["group_id"].drop_duplicates().tolist(), args.seed)
    train_df = df[df["group_id"].isin(train_groups)].copy()
    valid_df = df[df["group_id"].isin(valid_groups)].copy()
    test_df = df[df["group_id"].isin(test_groups)].copy()

    x_train = train_df[feature_cols].to_numpy(dtype=np.float32)
    y_train = train_df["target_score"].to_numpy(dtype=np.float32)
    x_valid = valid_df[feature_cols].to_numpy(dtype=np.float32)
    y_valid = valid_df["target_score"].to_numpy(dtype=np.float32)

    weights = make_weights(train_df)
    model = lgb.LGBMRegressor(
        objective="regression",
        n_estimators=650,
        learning_rate=0.035,
        num_leaves=31,
        max_depth=-1,
        min_child_samples=10,
        subsample=0.9,
        colsample_bytree=0.9,
        reg_alpha=0.05,
        reg_lambda=0.2,
        random_state=args.seed,
        n_jobs=-1,
    )

    model.fit(
        x_train,
        y_train,
        sample_weight=weights,
        eval_set=[(x_valid, y_valid)],
        eval_metric="l2",
        callbacks=[lgb.early_stopping(60), lgb.log_evaluation(50)],
    )

    for split_name, split_df in [("train", train_df), ("valid", valid_df), ("test", test_df)]:
        split_df = split_df.copy()
        split_df["prediction"] = clip01(model.predict(split_df[feature_cols].to_numpy(dtype=np.float32)))
        report = evaluate_groups(split_df)
        write_json(output_dir / f"{split_name}_validation_report.json", report)
        print(f"{split_name}: {json.dumps(report['summary'], ensure_ascii=False, sort_keys=True)}")

    test_report = json.loads((output_dir / "test_validation_report.json").read_text(encoding="utf-8"))
    false_repair_rate = test_report["summary"]["falseRepairRate"]
    if false_repair_rate > args.max_false_repair_rate:
        print(
            f"false repair rate {false_repair_rate:.6f} exceeds limit {args.max_false_repair_rate:.6f}",
            file=sys.stderr,
        )
        return 20

    booster_path = output_dir / "AFR.GlyphCore.Model.txt"
    model.booster_.save_model(str(booster_path))

    manifest = build_manifest(features_path, df, test_report)
    write_json(output_dir / "AFR.GlyphCore.ModelManifest.json", manifest)

    if not args.skip_onnx:
        export_onnx(model, output_dir / "AFR.GlyphCore.Model.onnx", FEATURE_COUNT, args.opset, manifest)

    write_json(
        output_dir / "training_summary.json",
        {
            "aiDisplayName": AI_DISPLAY_NAME,
            "aiInternalName": AI_INTERNAL_NAME,
            "author": AUTHOR_NAME,
            "featureRows": int(len(df)),
            "groups": int(df["group_id"].nunique()),
            "trainGroups": len(train_groups),
            "validGroups": len(valid_groups),
            "testGroups": len(test_groups),
            "featureSchemaVersion": FEATURE_SCHEMA_VERSION,
            "modelManifest": portable_path(output_dir / "AFR.GlyphCore.ModelManifest.json"),
            "onnxModel": portable_path(output_dir / "AFR.GlyphCore.Model.onnx"),
        },
    )
    return 0


def split_groups(groups: list[str], seed: int) -> tuple[set[str], set[str], set[str]]:
    import random

    rng = random.Random(seed)
    groups = list(groups)
    rng.shuffle(groups)
    total = len(groups)
    train_end = max(1, int(total * 0.70))
    valid_end = max(train_end + 1, int(total * 0.85))
    return set(groups[:train_end]), set(groups[train_end:valid_end]), set(groups[valid_end:])


def portable_path(path: Path) -> str:
    resolved = path.resolve()
    for candidate in [ROOT, *ROOT.parents]:
        if (candidate / "CADFontAutoReplace.slnx").exists():
            try:
                return resolved.relative_to(candidate).as_posix()
            except ValueError:
                break
    return str(resolved)


def make_weights(df):
    import numpy as np

    weights = np.ones(len(df), dtype=np.float32)
    weights += np.where(df["label_action"] != "repair", 1.5, 0.0)
    weights += np.where(df["is_positive"] == 1, 2.0, 0.0)
    weights += np.where((df["label_action"] != "repair") & (df["is_noop"] == 0), 1.0, 0.0)
    return weights


def clip01(values):
    import numpy as np

    return np.clip(values, 0.0, 1.0)


def evaluate_groups(df) -> dict:
    details = []
    false_repairs = 0
    correct_repairs = 0
    missed_repairs = 0
    expected_repairs = 0
    skipped = 0

    for group_id, group in df.groupby("group_id", sort=False):
        group = group.sort_values("prediction", ascending=False)
        best = group.iloc[0]
        second_score = float(group.iloc[1]["prediction"]) if len(group) > 1 else 0.0
        margin = float(best["prediction"]) - second_score
        decision = decide(best, margin, group)
        expected_repair = str(best["label_action"]) == "repair"
        if expected_repair:
            expected_repairs += 1

        correct = (
            decision == "repair"
            and expected_repair
            and str(best["candidate_text"]) == str(best["label_text"])
        )
        false_repair = decision == "repair" and not correct

        if correct:
            correct_repairs += 1
        elif expected_repair and decision != "repair":
            missed_repairs += 1
        if false_repair:
            false_repairs += 1
        if decision != "repair":
            skipped += 1

        details.append(
            {
                "groupId": group_id,
                "labelAction": str(best["label_action"]),
                "decision": decision,
                "bestText": str(best["candidate_text"]),
                "labelText": str(best["label_text"]),
                "score": float(best["prediction"]),
                "margin": margin,
                "source": str(best["source"]),
                "correct": correct,
                "falseRepair": false_repair,
            }
        )

    group_count = len(details)
    return {
        "summary": {
            "groups": group_count,
            "expectedRepairs": expected_repairs,
            "correctRepairs": correct_repairs,
            "missedRepairs": missed_repairs,
            "falseRepairs": false_repairs,
            "skipped": skipped,
            "repairRecall": safe_div(correct_repairs, expected_repairs),
            "falseRepairRate": safe_div(false_repairs, group_count),
        },
        "details": details,
    }


def decide(best, margin: float, group) -> str:
    current_unsafe = (
        float(group.iloc[0]["f09_current_control_ratio"]) > 0
        or float(group.iloc[0]["f11_current_replacement_ratio"]) > 0
        or float(group.iloc[0]["f38_current_has_suspicious_unicode"]) > 0
        or int(group.iloc[0]["is_from_xref"]) == 1
    )
    if current_unsafe:
        return "unsafe"
    if int(best["is_noop"]) == 1:
        return "skip"
    if int(best["is_roundtrip"]) != 1:
        return "unsafe"
    if (
        float(best["f10_candidate_control_ratio"]) > 0
        or float(best["f12_candidate_replacement_ratio"]) > 0
        or float(best["f37_candidate_has_suspicious_unicode"]) > 0
    ):
        return "unsafe"
    if float(best["prediction"]) < MINIMUM_CONFIDENCE:
        return "skip"
    if margin < MINIMUM_SCORE_MARGIN:
        return "skip"
    return "repair"


def safe_div(numerator: int, denominator: int) -> float:
    if denominator <= 0:
        return 0.0
    return float(numerator) / float(denominator)


def build_manifest(features_path: Path, df, test_report: dict) -> dict:
    now = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return {
        "aiDisplayName": AI_DISPLAY_NAME,
        "aiInternalName": AI_INTERNAL_NAME,
        "aiPurpose": "AFR DBText local conservative repair decision model",
        "author": {
            "name": AUTHOR_NAME,
            "email": AUTHOR_EMAIL,
            "github": PROJECT_GITHUB,
            "gitee": PROJECT_GITEE,
        },
        "modelVersion": f"dbtext-ai-lightgbm-{now}",
        "featureSchemaVersion": FEATURE_SCHEMA_VERSION,
        "featureCount": FEATURE_COUNT,
        "inputName": "features",
        "outputName": "variable",
        "scoreKind": "candidate-score-0-1",
        "trainer": "LightGBMRegressor",
        "trainingDataHash": sha256_file(features_path),
        "trainingRows": int(len(df)),
        "trainingGroups": int(df["group_id"].nunique()),
        "minimumConfidence": MINIMUM_CONFIDENCE,
        "minimumScoreMargin": MINIMUM_SCORE_MARGIN,
        "validationSummary": test_report["summary"],
        "createdUtc": now,
        "privateModel": False,
        "distribution": "public-training-artifact",
    }


def export_onnx(model, output_path: Path, feature_count: int, opset: int, manifest: dict) -> None:
    try:
        from onnxmltools import convert_lightgbm
        from onnxmltools.convert.common.data_types import FloatTensorType
    except ImportError as ex:
        raise RuntimeError(
            "ONNX export dependencies are missing. Install requirements.txt or pass --skip-onnx."
        ) from ex

    onnx_model = convert_lightgbm(
        model,
        initial_types=[("features", FloatTensorType([None, feature_count]))],
        target_opset=opset,
    )
    onnx_model.producer_name = "CADFontAutoReplace GlyphCore DBText training pipeline"
    onnx_model.doc_string = f"{AI_DISPLAY_NAME}: AFR DBText local conservative repair decision model."
    add_onnx_metadata(
        onnx_model,
        {
            "aiDisplayName": manifest["aiDisplayName"],
            "aiInternalName": manifest["aiInternalName"],
            "aiPurpose": manifest["aiPurpose"],
            "authorName": manifest["author"]["name"],
            "authorEmail": manifest["author"]["email"],
            "projectGitHub": manifest["author"]["github"],
            "projectGitee": manifest["author"]["gitee"],
            "modelVersion": manifest["modelVersion"],
            "featureSchemaVersion": manifest["featureSchemaVersion"],
            "trainingDataHash": manifest["trainingDataHash"],
            "privateModel": str(manifest["privateModel"]).lower(),
            "distribution": manifest["distribution"],
        },
    )
    output_path.write_bytes(onnx_model.SerializeToString())
    print(f"wrote ONNX model to {output_path}")


def add_onnx_metadata(onnx_model, metadata: dict[str, str]) -> None:
    del onnx_model.metadata_props[:]
    for key, value in metadata.items():
        prop = onnx_model.metadata_props.add()
        prop.key = str(key)
        prop.value = str(value)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as reader:
        for chunk in iter(lambda: reader.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
